groups:
- name: traefik-lab
  rules:
  - alert: TraefikHigh5xx
    expr: (sum by (service) (rate(traefik_service_requests_total{job="traefik-lab",code=~"5.."}[1m]))
      / sum by (service) (rate(traefik_service_requests_total{job="traefik-lab"}[1m]))
      > 0.05) and on(service) (sum by(service) (rate(traefik_service_requests_total{job="traefik-lab"}[1m]))
      > 0.1)
    for: 20s
    labels:
      severity: warning
    annotations:
      summary: Traefik service {{ $labels.service }} 5xx exceeds 5%
