entryPoints:
  websecure:
    address: :443
providers:
  file:
    filename: /routes.yml
certificatesResolvers:
  cloudflare-staging:
    acme:
      email: REPLACE_WITH_YOUR_EMAIL
      storage: /acme/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - 1.1.1.1:53
        - 8.8.8.8:53
        propagation:
          delayBeforeChecks: 10s
