entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
      - 172.30.39.11/32
    http:
      sanitizePath: true
  websecure:
    address: :443
  metrics:
    address: :9100
  echo:
    address: :7000
  echotls:
    address: :7443
  dns:
    address: :5353/udp
    udp:
      timeout: 3s
providers:
  file:
    directory: /dynamic
    watch: true
  consulCatalog:
    endpoint:
      address: consul:8500
      scheme: http
    exposedByDefault: false
    refreshInterval: 2s
log:
  level: INFO
  format: json
accessLog:
  format: json
metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
tracing:
  serviceName: traefik-review
  sampleRate: 1.0
  otlp:
    grpc:
      endpoint: otel:4317
      insecure: true
